language: go

go:
  - "1.11"

services:
  - docker

before_install:
  - nvm install --lts
  - npm i -g npm
  - npm ci
  - go get -u github.com/gobuffalo/packr/packr

after_success:
  # docker login is required if you want to push docker images.
  # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
  # - test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
