on: push
name: Test
jobs:
  npm-test:
    name: npm test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm test
        uses: actions/setup-node@v1
      - name: Run NPM Tests
        run: npm it
  go-test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Go Tests
        run: go test -cover ./...
  docker-build:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose -f integration/docker-compose.test.yml run integration
